baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "purple"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "ASB :D"
    subtitle = "An incredible blog made by Avunit"
    keywords = ""
    copyright = ""
    menuMore = "Show more incredible posts"
    readMore = "Read more mirific posts"
    readOtherPosts = "Read other fabulous posts"

    [languages.en.params.logo]
      logoText = "Avunit's Staggering Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "main"
        name = "main site"
        url = "https://avunit.tk"
      [[languages.en.menu.main]]
        identifier = "troll"
        name = "troll site"
        url = "https://troll.avunit.tk/"
